version: "3.9"
services:
  frontend:
    build: .
    ports: 
      - 80:80
  backend:
    image: ghcr.io/massih/starforks-backend:latest
    ports:
      - 8080:8080
    depends_on: 
      - db
  db:
    container_name: starforks-db
    image: postgres:13.3
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=starforks
    ports:
      - "5432:5432"