version: "3.9"
services:
  frontend:
    build: .
    ports:
      - 80:80
    environment:
      - API_URL=http://localhost:8080/recipe
  # backend:
  #   image: ghcr.io/massih/starforks-backend:latest
  #   ports:
  #     - 8080:8080
  #   environment:
  #     - JDBC_URL=jdbc:postgresql://db:5432/starforks
  #     - JDBC_USER=admin
  #     - JDBC_PASSWORD=admin
  #     - JDBC_DRIVER=org.postgresql.Driver
  #   depends_on:
  #     - db
  db:
    container_name: starforks-db
    image: postgres:13.3
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=starforks
    ports:
      - "5432:5432"
  mongo:
    container_name: mongo
    image: mongo:5.0.5
    environment:
      - MONGO_INITDB_DATABASE=starforks
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - "27017:27017"
