version: "3.9"
services:
  frontend:
    build: .
    ports: 
      - 80:80
    environment:
      - API_URL=http://backend:8080/
  backend:
    image: ghcr.io/massih/starforks-backend:latest
    ports:
      - 8080:8080
    environment:
      - JDBC_URL=jdbc:postgresql://db:5432/starforks
      - JDBC_USER=admin
      - JDBC_PASSWORD=admin
      - JDBC_DRIVER=org.postgresql.Driver
    depends_on: 
      - db
  db:
    container_name: starforks-db
    image: postgres:13.3
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=starforks
    ports:
      - "5432:5432"